### PR TITLE
Fix connector to work with years before 1000

### LINKED ISSUE #184: DatePicker with two digit year and dates before year 1000
### Description
I just had a look at the date picker using https://vaadin.com/components/vaadin-date-picker/java-examples

I'd like to enter a date in a shorter way for example using a two digit year format like 1.1.19 (in german date format for 1st January 2019). In java there is a common way to transform two digit year in the range of -79/+20 years from now.

Entering a two digit year simply comes to an invalid date.

### Expected outcome
I expect to be able to enter a two digit year wich is transformed to the common range of -79/+20 years from now.

Even more I expect to get a valid date when I enter a year before year 1000 using the leading zero, like 0021, wich simply is transformed to 1921! Years between 100 and 999 are not accepted at all.

### Actual outcome
Two digit year is not excepted at all. Years before 1000 can not be entered or picked at all (at least in the example on https://vaadin.com/components/vaadin-date-picker/java-examples). Years with one leading zero is always invalid. Years with two leading zero (like 0021) is transformed to 1921.

### Live Demo
https://vaadin.com/components/vaadin-date-picker/java-examples

### Steps to reproduce
Got ot https://vaadin.com/components/vaadin-date-picker/java-examples

01/01/21 --> not accepted, shoule be interpreded as 01/01/2021
01/01/79 --> not accepted, shoule be interpreded as 01/01/1979 
01/01/0021 --> 01/01/1921, should be 01/01/0021 (simply don't touch!)
01/01/0121 --> not accepted, should be 01/01/0121 (simply don't touch!)

### PR DESCRIPTION
**Pull request by Haprog**
- Fix formatDate() to work with years before 1000
- Fix parseDate() to work with years when they are input with less than 4 digits. parseDate() now accepts years with 1-4 digits.

Fixes #184

(This is a new version of the PR #230. This only has minimal changes to fix the issue without extra improvements.)

### CODE REVIEW

File: vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js [hunk 1]
```diff
@@ -97,19 +97,29 @@
...
                 datepicker.i18n.formatDate = tryCatchWrapper(function (date) {
-                    let rawDate = new Date(Date.UTC(date.year, date.month, date.day));
-                    return cleanString(rawDate.toLocaleDateString(locale, { timeZone: 'UTC' }));
+                    let rawDate = datepicker._parseDate(`${date.year}-${date.month + 1}-${date.day}`);
+
+                    // Workaround for Safari DST offset issue when using Date.toLocaleDateString().
+                    // This is needed to keep the correct date in formatted result even if Safari
+                    // makes an error of an hour or more in the result with some past dates.
+                    // See https://github.com/vaadin/vaadin-date-picker-flow/issues/126#issuecomment-508169514
+                    rawDate.setHours(12)
```
Comment (Haprog) [inline vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js:120]: This is needed to avoid reintroducing a bug. See https://github.com/vaadin/vaadin-date-picker-flow/issues/126#issuecomment-508169514

I found this `setHours(12)` to be a simpler workaround in this context without needing to use `Date.UTC` and `{ timeZone: 'UTC' }`. I tested this with iOS 13 Safari. Without this workaround it's impossible to select some dates like `1966-06-01` on iPhone (and desktop Safari) if the system region has been set to e.g. Finland. With this workaround it works.

Would be awesome to have an automated test for this issue but afaik Flow component integration tests are not run with Safari so it's not possible to test with the current setup.

Comment (tomivirkki) [reply vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js:120]: I wonder if something like this is an option? It replaces the date values in the formatted sample date so there's no Date object in use at all.

```js
datepicker.i18n.formatDate = tryCatchWrapper(function (date) {
    return testString
        .replace(datepicker.$connector.dayPart.initial, date.day)
        .replace(datepicker.$connector.monthPart.initial, date.month + 1)
        .replace(datepicker.$connector.yearPart.initial, date.year);
});
```

Comment (Haprog) [reply vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js:120]: The above at least wouldn't automatically add leading zeroes to day and month (when less than 10) which is used in some locales.

Comment (tomivirkki) [reply vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js:120]: We could change the day/month values used for the sample to something that have zeros in case required. Like 2 and 3.

Comment (tomivirkki) [reply vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js:120]: Note that the suggestion above doesn't work as such also in case `date.day` has the same value as `datepicker.$connector.monthPart.initial`. The second replace would affect the day instead of the month in that case. We would need to use the `part.index` instead of just replace. Not sure if all this would add too much additional logic vs not having to deal with timezones.

Comment (Haprog) [reply vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js:120]: Imo it would be unnecessary complexity to add such logic compared to current status. This is not dealing with timezones now (it's just local time like it is on the web component too). This is now just setting time to `12.00` for formatting the date preventing off by 1 hour errors in Safari (which can cause wrong date if the time is near midnight).
