### PR TITLE
Don't set initial value of there is Element has property value

### LINKED ISSUE #274: It's not possible to instantiate `GeneratedVaadinDatePicker` subclass whose value is based on the underlying Element value
This is failing test:

```
 private static class TestDatePicker
            extends GeneratedVaadinDatePicker<TestDatePicker, LocalDate> {

        TestDatePicker() {
            super(TEST_VALUE, null, String.class, value -> null, value -> null);
        }
    }

@Test
    public void elementHasValue_wrapIntoField_propertyIsNotSetToInitialValue() {
        Element element = new Element("vaadin-date-picker");
        element.setProperty("value", "2007-12-03");
        UI ui = new UI();
        UI.setCurrent(ui);
        VaadinSession session = Mockito.mock(VaadinSession.class);
        ui.getInternals().setSession(session);
        VaadinService service = Mockito.mock(VaadinService.class);
        Mockito.when(session.getService()).thenReturn(service);

        Instantiator instantiator = Mockito.mock(Instantiator.class);

        Mockito.when(service.getInstantiator()).thenReturn(instantiator);

        Mockito.when(instantiator.createComponent(TestDatePicker.class))
                .thenAnswer(invocation -> new TestDatePicker());

        TestDatePicker field = Component.from(element, TestDatePicker.class);
        Assert.assertEquals("2007-12-03",
                field.getElement().getPropertyRaw("value"));
    }
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #274

### CODE REVIEW

File: vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java [hunk 1]
```diff
@@ -81,7 +81,37 @@ public DatePicker() {
      * @see #setValue(Object)
      */
     public DatePicker(LocalDate initialDate) {
-        super(initialDate, null, String.class, PARSER, FORMATTER);
+        super(initialDate, null, String.class, PARSER, FORMATTER, false);
```
Comment (mshabarov) [inline vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java:84]: Call `this(initialDate, false)` instead

File: vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java [hunk 2]
```diff
@@ -1190,11 +1190,12 @@ protected void removeAll() {
     public <P> GeneratedVaadinDatePicker(T initialValue, T defaultValue,
             Class<P> elementPropertyType,
             SerializableFunction<P, T> presentationToModel,
-            SerializableFunction<T, P> modelToPresentation) {
+            SerializableFunction<T, P> modelToPresentation,
+            boolean isInitialValueOptional) {
```
Comment (mshabarov) [inline vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java:1194]: Add `isInitialValueOptional` to javadoc

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java (hunk 1 above)
Comment (denis-anisimov) [reply vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java:84]: Leftover, thanks.

**Review by mshabarov — APPROVED** [review]
